name: build and push

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    # checkout the repository
    - name: checkout repository
      uses: actions/checkout@v1
    
    # setup nuget
    - name: setup nuget
      # You may pin to the exact commit or the version.
      # uses: NuGet/setup-nuget@04b0c2b8d1b97922f67eca497d7cf0bf17b8ffe1
      uses: NuGet/setup-nuget@v1.0.5
      with:
        # NuGet API Key to configure.
        nuget-api-key: https://nuget.pkg.github.com/josepfranco/index.json
        # Source to scope the NuGet API Key to.
        nuget-api-key-source: ${{ secrets.GH_PACKAGES_TOKEN }}
      
    # build the binaries
    - name: build with dotnet
      run: dotnet build --configuration Release --version-suffix prerelease-$(date +%Y%m%d%H%M%S) -o "./BUILDS/Release/"
      shell: bash
    
    # publish to github packages nuget
    - name: publish to packages
      # uses: brandedoutcast/publish-nuget@c12b8546b67672ee38ac87bea491ac94a587f7cc
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: ./BUILDS/Release/
        NUGET_KEY: ${{ secrets.GH_PACKAGES_TOKEN }}
        NUGET_SOURCE: https://nuget.pkg.github.com/josepfranco/index.json
